version: '3.7'

services:
  db:
    image: mysql:8.0.19
    environment:
      MYSQL_DATABASE: todos
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - datavolume:/var/lib/mysql
    restart: unless-stopped
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: todos
      DB_PASS: password
      DB_PORT: 3306
      DB_USER: db_user
    restart: unless-stopped
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    depends_on:
      - "backend"
    restart: unless-stopped
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
volumes:
  datavolume:
